let userData = [
    {
        id: 1,
        firstname: 'Михаил',
        lastname: 'Зубенко',
        middlename: 'Петрович',
        img: 'photo.jpg',
        age: '40',
        birthday: '25.09.2003',
        sex: 'Мужчина',
        quality: 'Неоконченное среднее',
        post: 'Мафиозник',
        experience: '20',
        salary: '50',
        email: 'diplom@gmail.com',
        phone: '+78005553535',
        userGroups: ['Админ', 'Модератор сайта'],
        login: 've4ern1k',
        password: '123'
    },
    {
        id: 2,
        firstname: 'Райан',
        lastname: 'Гослинг',
        middlename: 'Томас',
        img: 'photo1.jpg',
        age: '43',
        birthday: '12.11.1980',
        sex: 'Мужчина',
        quality: 'Предельно высшее',
        post: 'Driver',
        experience: '10',
        salary: '100000',
        email: 'diplom@gmail.com',
        phone: '+78005553535',
        userGroups: ['Админ', 'Модератор сайта'],
        login: 'aboba',
        password: '86'
    },
    {
        id: 3,
        firstname: 'Морская',
        lastname: 'Наталья',
        middlename: 'Пехота',
        img: 'photo2.jpg',
        age: '65',
        birthday: '01.01.2024',
        sex: 'Женщина',
        quality: 'Неоконченное высшее',
        post: 'Пассажир',
        experience: '5',
        salary: '5',
        email: 'diplom@gmail.com',
        phone: '+78005553535',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 4,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 5,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 6,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 7,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 8,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 9,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 10,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 11,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 12,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 13,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 14,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 15,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
    {
        id: 16,
        firstname: 'Иван',
        lastname: 'Иванов',
        middlename: 'Иванович',
        img: '',
        age: '1',
        birthday: '01.01.2000',
        sex: 'Мужчина',
        quality: 'Высшее',
        post: 'Работник',
        experience: '1',
        salary: '1',
        email: 'diplom@gmail.com',
        phone: '+79999999999',
        userGroups: ['Админ', 'Модератор сайта']
    },
]

export default userData